services:
    back-end:
        image: crypticend/bingo-back-end:latest
        container_name: bingo-backend
        restart: always
        ports:
            - 8080:8080
        environment:
            spring.datasource.url: jdbc:mysql://database:3306/bingo
            spring.datasource.username: java
            spring.datasource.password: /run/secrets/db_password
            logging.level.root: INFO
        secrets:
            - db_password
    front-end:
        image: crypticend/bingo-front-end:latest
        container_name: bingo-frontend
        restart: always
        environment:
            REACT_APP_CONNECTION_URL: http://crypticend.myds.me:8080/api
        ports:
            - 32770:32770
        depends_on:
            - back-end

secrets:
    db_password:
      file: secrets/db_password.txt

networks:
    default:
        external:
            name: bingo